<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\SrUserAdmin\Utils\SrUserAdminTrait;
use srag\RemovePluginDataConfirm\SrUserAdmin\AbstractRemovePluginDataConfirm;

/**
 * Class SrUserAdminRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrUserAdminRemoveDataConfirm: ilUIPluginRouterGUI
 */
class SrUserAdminRemoveDataConfirm extends AbstractRemovePluginDataConfirm {

	use SrUserAdminTrait;
	const PLUGIN_CLASS_NAME = ilSrUserAdminPlugin::class;
}
