<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\SrUserAdmin\Config\ConfigFormGUI;
use srag\Plugins\SrUserAdmin\Utils\SrUserAdminTrait;
use srag\ActiveRecordConfig\SrUserAdmin\ActiveRecordConfigGUI;

/**
 * Class ilSrUserAdminConfigGUI
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrUserAdminConfigGUI extends ActiveRecordConfigGUI {

	use SrUserAdminTrait;
	const PLUGIN_CLASS_NAME = ilSrUserAdminPlugin::class;
	/**
	 * @var array
	 */
	protected static $tabs = [ self::TAB_CONFIGURATION => ConfigFormGUI::class ];
}
