<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\SrUserAdmin\Utils\SrUserAdminTrait;
use srag\DIC\SrUserAdmin\DICTrait;
use srag\Plugins\SrUserAdmin\Config\Config;

/**
 * Class ilSrUserAdminUIHookGUI
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrUserAdminUIHookGUI extends ilUIHookPluginGUI {

	use DICTrait;
	use SrUserAdminTrait;
	const PLUGIN_CLASS_NAME = ilSrUserAdminPlugin::class;
	const USER_ADMIN_LOADER = "usr_admin_loader";
	const PAR_TABS = "tabs";

	/**
	 * @var bool[]
	 */
	protected static $load = [
		self::USER_ADMIN_LOADER => false,
	];


	/**
	 * ilSrUserAdminUIHookGUI constructor
	 */
	public function __construct() {

	}


	/**
	 * @param string $a_comp
	 * @param string $a_part
	 * @param array  $a_par
	 *
	 * @return array
	 */
	public function modifyGUI(/*string*/
		$a_comp, /*string*/
		$a_part, /*array*/
		$a_par = []): array {
		/*self::dic()->ctrl()->getLinkTargetByClass([
			ilUIPluginRouterGUI::class,
			SrUserAdminGUI::class
		], SrUserAdminGUI::CMD_SOME);*/


		if ($a_part === self::PAR_TABS &&
			strtolower(self::dic()->ctrl()->getCmdClass()) == "ilobjuserfoldergui"
			&& !self::$load[self::USER_ADMIN_LOADER]
			&& in_array(Config::getField(Config::KEY_ROLE_OBJ_ID),self::dic()->rbacreview()->assignedGlobalRoles(self::dic()->user()->getId()))) {


			self::$load[self::USER_ADMIN_LOADER] = true;
			self::dic()->mainTemplate()->addCss(self::plugin()->directory() . "/css/sruseradmin.css");


			$table_prop = new ilTablePropertiesStorage();

			$table_prop->storeProperty('user7',self::dic()->user()->getId(),'selfields','a:27:{s:9:"firstname";b:1;s:8:"lastname";b:1;s:12:"access_until";b:0;s:10:"last_login";b:0;s:11:"create_date";b:0;s:12:"approve_date";b:0;s:10:"agree_date";b:0;s:5:"email";b:1;s:12:"second_email";b:0;s:5:"title";b:0;s:8:"birthday";b:0;s:6:"gender";b:0;s:9:"org_units";b:0;s:11:"institution";b:0;s:10:"department";b:0;s:6:"street";b:0;s:7:"zipcode";b:0;s:4:"city";b:0;s:7:"country";b:0;s:11:"sel_country";b:0;s:12:"phone_office";b:0;s:10:"phone_home";b:0;s:12:"phone_mobile";b:0;s:3:"fax";b:0;s:13:"matriculation";b:0;s:9:"auth_mode";b:0;s:5:"udf_5";b:0;}');

			$table_prop->showFilter();
			$table_prop->storeProperty('user7',self::dic()->user()->getId(),'filter',1);


		}


		return [ "mode" => self::KEEP, "html" => "" ];
	}
}
