<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\SrUserAdmin\Utils\SrUserAdminTrait;
use srag\DIC\SrUserAdmin\DICTrait;

/**
 * Class SrUserAdminGUI
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrUserAdminGUI: ilUIPluginRouterGUI
 */
class SrUserAdminGUI {

	use DICTrait;
	use SrUserAdminTrait;
	const PLUGIN_CLASS_NAME = ilSrUserAdminPlugin::class;
	const CMD_SOME = "role_obj_id";


	/**
	 * SrUserAdminGUI constructor
	 */
	public function __construct() {

	}


	/**
	 *
	 */
	public function executeCommand()/*: void*/ {
		$next_class = self::dic()->ctrl()->getNextClass($this);

		switch (strtolower($next_class)) {
			default:
				$cmd = self::dic()->ctrl()->getCmd();

				switch ($cmd) {
					case self::CMD_SOME:
						$this->{$cmd}();
						break;
					default:
						break;
				}
				break;
		}
	}


	/**
	 *
	 */
	protected function some()/*: void*/ {
		self::output()->output("some", true);
	}
}
