<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrUserAdmin\Config;

use srag\Plugins\SrUserAdmin\Utils\SrUserAdminTrait;
use ilSrUserAdminPlugin;
use srag\ActiveRecordConfig\SrUserAdmin\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @package srag\Plugins\SrUserAdmin\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig {

	use SrUserAdminTrait;
	const TABLE_NAME = "ui_uihk_srusr_config";
	const PLUGIN_CLASS_NAME = ilSrUserAdminPlugin::class;
	const KEY_ROLE_OBJ_ID = "role_obj_id";
	/**
	 * @var array
	 */
	protected static $fields = [
		self::KEY_ROLE_OBJ_ID => self::TYPE_INTEGER
	];
}
